# render.yaml

services:
  - type: web
    name: nextjs-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_GET_PROPERTIES_URL
        value: https://my-rentify-0zyb.onrender.com/api/properties/
      - key: NEXT_PUBLIC_BASE_URL
        value: https://my-rentify-0zyb.onrender.com
    domains:
      - https://rentify-dtwu.onrender.com
